### ISSUE TITLE
Remote eye service is not working

### ISSUE THREAD

**Issue by jbyu** [VCL3D/VolumetricCapture#10]
I follow the instruction: installed RabbitMQ and open 5672,11234 port on work station and min-PCs. 
Download remote_eye.zip and extract to C:/Capturer, then install service with administrator.
But the devices won't show up.
I use Volumetric Capture and Tools Release 3.0 and remote_eye.zip 2.0
Thank you.

**Comment by ankarako** [comment]
Hi @jbyu , did you install the Service on all the mini-PCs?

**Comment by jbyu** [comment]
I just tested one mini-PC.
1. The service is running.
2. The log shows no request from the workstation. It only shows
[timestamp]: Listener started listening...
[timestamp]: Process name: C:/Capturer/bin/remote_eye.exe
3. I can manually open remote_eye and connect to the workstation.

**Comment by ankarako** [comment]
Did you open port 11234 on UDP or TCP protocol? (It should be UDP, just saw that in the wiki this is omitted)

**Comment by jbyu** [comment]
Yes, UDP is the key! Thank you.

**Comment by ankarako** [comment]
Happy to help.
