### ISSUE TITLE
Volumetric Capture without NUCs

### ISSUE THREAD

**Issue by AbsterZhu** [VCL3D/VolumetricCapture#101]
Hi, I currently have a high-performance PC and 4 Azure Kinect cameras. Can I directly connect the 4 cameras via USB to achieve volumetric capture? If possible, how should I set it up?

**Comment by ankarako** [comment]
Hi, thanks for your interest in our project.
Unfortunately device connection via USB directly is not supported. Additionally, we are not developing for Kinect4Azure anymore as Microsoft discontinued them (again).
