### ISSUE TITLE
D435 sensors support?

### ISSUE THREAD

**Issue by cleoag** [VCL3D/VolumetricCapture#12]
Will it work with D435 depth sensors?

**Comment by vladsterz** [comment]
Hello @cleoag ,
it should work since D415 and D435 share the same API, but we haven't tested it.
I can add it to our TODO list and we can try it next week.
Vlad

**Comment by zuru** [comment]
Actually, D435 are not supported (their resolutions are not configured from the app). 
Given that the focus in on closer distance volumetric capture, the D415 are more appropriate sensors.
We will also be releasing a Kinect 4 Azure update soonish.
