### ISSUE TITLE
Assistance with Azure Kinect support 

### ISSUE THREAD

**Issue by tylergibson** [VCL3D/VolumetricCapture#13]
Hi all, you've noted in your readme that Azure Kinect support is in progress.  If desired, I would love to collaborate / help in any form.  I have a 5 K4A camera setup and have been working on my own solution. Your repo seems to already have the vast majority of plumbing I have been working on.

**Comment by zokin** [comment]
An early Kinect Azure release is now [available](https://github.com/VCL3D/VolumetricCapture/releases/tag/4.0.1).
