### ISSUE TITLE
do you still plan to support more than 4 sensors?

### ISSUE THREAD

**Issue by mhudnell** [VCL3D/VolumetricCapture#14]
Was just wondering if this was still planned in a future release, was considering using this setup but would be nice if we could add additional sensors.

**Comment by vladsterz** [comment]
Hello @mhudnell ,
Yes, we still plan to extend our platform to support more than 4 sensors. We are not working on it in a full time manner, so it is not around the corner, but should not take too long. It will be released along with Kinect Azure support. :)
