### ISSUE TITLE
Intel Realsense 435 compatibility?

### ISSUE THREAD

**Issue by V0L4T1LE** [VCL3D/VolumetricCapture#16]
Your documentation lists Intel Realsense 415, are the 435 cameras also compatible?

Or are the results with the Kinect Azure cameras significantly better and worth waiting for that update to be pushed if I haven't yet ordered cameras?

**Comment by zuru** [comment]
Unfortunately, as also reported in [#12] we do not currently support D435. 
We focused on D415 as it outperforms the D435 in the close range capture use cases we are targeting.

Nevertheless, we are pushing for an early release of the K4A support (this week or the next), so your second option might be safer.
