### ISSUE TITLE
Azure Kinect mis-identified as Intel camera

### ISSUE THREAD

**Issue by tylergibson** [VCL3D/VolumetricCapture#22]
Camera appears in volumetric_capture as a camera:
![image](https://user-images.githubusercontent.com/1085397/80328452-389ffb00-87f4-11ea-8c71-d004d3feb565.png)
but when selecting "Connect", the application crashes and the remote_eye.exe crashes as well with the following:
![image](https://user-images.githubusercontent.com/1085397/80328505-5ff6c800-87f4-11ea-80d1-d675d4be0e07.png)

It appears I need to manually specify that the camera is an Azure Kinect, but I cannot do this due to #21

**Comment by zokin** [comment]
Can you please verify that these (central volumetric capture and remote eye) are not running on the same machine?

Currently this is not supported due to socket port conflicts.

**Comment by tylergibson** [comment]
Ah they were running on the same machine.  I will attempt on separate machines, although all the rabbitmq bits seem to work just fine.

**Comment by zuru** [comment]
This is due to ptp sync needing UDP networking rather than the broker (RMQ) which handles the rest of the communication with the sensors.
Please let me know whether the issue persists or if  this is now resolved in order to close it.

**Comment by zuru** [comment]
This has been fixed in the latest release, there is no port conflict and the same workstation can accommodate the `volcap` application as well as an `eye`.
