### ISSUE TITLE
Incorrect path for device_repository.json in wiki

### ISSUE THREAD

**Issue by sergiobd** [VCL3D/VolumetricCapture#24]
Hi,

I followed the instructions in the wiki. According to https://github.com/VCL3D/VolumetricCapture/wiki/Calibration-&-Setup-for-Kinect-Azure, 

The device_repository.json file should be placed under `"path_to_volumetric_capture"/Data/Executables/Calibration/multisensor_calibration/Resources/data`

However, when placed there, I get the following error:
```
device_repository.json does not exist. Throwing. Assertion triggered.
Assertion failed: false, file D:\Projects\vs\RealSenz\immerzion\include\io\device_repository_loader.h, line 101
```

I found that if I place the file besides ```volumetric_capture.exe ```, the application does run.

**Comment by zuru** [comment]
Hi Sergio,

the `device_repository.json` needs to be visible to both the application (relative/local to the `volumetric_capture.exe`) and the calibration script (at `multisensor_calibration/Resources/data`).
We have fixed this (it will only need to be local to the `volumetric_capture.exe`) and will include it in another update, but for now, you just need to copy/paste it to both locations.
