### ISSUE TITLE
3 kinects 1 workstation

### ISSUE THREAD

**Issue by pajama** [VCL3D/VolumetricCapture#27]
I have a powerful workstation with enough usb bandwidth to stream/record from 3 kinects. Can I setup 3 capturers on one station? Will the recorder find them locally with rabbitmq? Thanks!

**Comment by zuru** [comment]
Unfortunately running everything in the same system is not supported at the moment (see this [issue](https://github.com/VCL3D/VolumetricCapture/issues/22#issuecomment-619789308)).

We will update you in case this gets updated.
