### ISSUE TITLE
There doesnt seem to be any executables in the releases, only 200 megs of GIF images

### ISSUE THREAD

**Issue by chrisrogers3d** [VCL3D/VolumetricCapture#32]
The code section on github also seems to be just docs.

**Comment by tofis** [comment]
Hello @chrisrogers3d,

Can you let us know which version you downloaded? Obviously, all the released versions should contain executables. You can find all the versions in the [releases page](https://github.com/VCL3D/VolumetricCapture/releases).

**Comment by chrisrogers3d** [comment]
I found the executables in the releases, my mistake.
Still a bit confusing to go to github and download "core" or "source code" and get only docs..
I also *finally* realized this solution requires a computer per camera, so its not useful to me.
