### ISSUE TITLE
Pointclouds in Visualizer Grid Are Upside-Down

### ISSUE THREAD

**Issue by jessekirbs** [VCL3D/VolumetricCapture#34]
The pointclouds in my 3D visualizer grid-space are in strange orientations. Before calibration, they are sideways. After calibration, they are upside-down. Any ideas why this is happening? Is there a way to shift orientation? Here's a screencap:

![upsidedown](https://user-images.githubusercontent.com/8700046/89621334-06b42100-d846-11ea-902e-11da4be5be04.PNG)

**Comment by vladsterz** [comment]
Hello @jessekirbs ,
looks like you rotated your Kinect devices to the wrong direction. Try putting them sideways but on the other side.

**Comment by zuru** [comment]
This was an issue with the kinect 4 azure shaders, it should be fixed now in the latest release.
