### ISSUE TITLE
Using intel PC instead of mini PCs

### ISSUE THREAD

**Issue by noorfatma** [VCL3D/VolumetricCapture#35]
Hi, 

I am starting to explore Volumetric capture using D415 and VLC3D. Right now I do not have mini PCs. can i try with a PC instead of mini PC.

**Comment by zuru** [comment]
Yes, you can, as indicated in #23, NUCs are not necessary, they only provide a portable, easy-to-setup and lower-cost alternative.

**Comment by noorfatma** [comment]
Thank you so much for such a quick reply. I was searching through only open Issues. My bad. Thanks a ton.
