### ISSUE TITLE
Fix Documentation to Include VS C++ Redistributables Dependency 

### ISSUE THREAD

**Issue by mellinger** [VCL3D/VolumetricCapture#36]
The K4A remote eye app was silently crashing until I installed the Microsoft Visual C++ Redistributable for Visual Studio 2019 available here: https://visualstudio.microsoft.com/downloads/

LMK if you want me to add it to the docs via a PR or if you want to. 

Thanks!
Max

**Comment by zuru** [comment]
Thanks for the feedback Max, added this important detail that slipped by to the docs.
