### ISSUE TITLE
Add additional step to installing remote eye to documentation

### ISSUE THREAD

**Issue by mellinger** [VCL3D/VolumetricCapture#37]
In my experience, you have to run the Remote Eye app as an administrator once and OK the security dialog that appears before running the install script, otherwise the install script will fail. Might be nice to note this in the documentation.

**Comment by ankarako** [comment]
Hi @mellinger ,

Actually, there is no install script for the `remote_eye` application. Is there a chance that you mean the **Monitor** Service (i.e. the `remote_eye_service` Windows Service? If so, we mention in the [documentation](https://vcl3d.github.io/VolumetricCapture/docs/software/#service--eye) that you need to run the installation script with administrator rights.

Best,
Antonis

**Comment by mellinger** [comment]
Hi! In my experience, you have to run remote_eye_service.exe as an administrator and OK the security warning once BEFORE you run the install script as an administrator, otherwise you get an error.

**Comment by ankarako** [comment]
Hi @mellinger,

Is there a chance that you had already installed the `remote_eye_service` from the previous version? Then you'll have to uninstall it (by running the uninstall script with administrator rights) and then run the install script for the new version.
I'll make sure we add this in the documentation.

Best,
Antonis

**Comment by mellinger** [comment]
On one, but not on the other 3.

**Comment by ankarako** [comment]
Hi @mellinger,

If you want you can make a pull request and document it in the "Software Setup" section to further discuss it there. ;)

Best, 
Antonis

**Comment by ankarako** [comment]
closing as the uninstall step has been documented and further steps will be discussed in the pull request
