### ISSUE TITLE
Device Repository Tool - Assertion failed

### ISSUE THREAD

**Issue by martinpro** [VCL3D/VolumetricCapture#43]
After starting dev_repo.exe with listing command

![Volcap Issue](https://user-images.githubusercontent.com/14353752/107547942-59441080-6bce-11eb-8fc6-6c53192d157f.jpg)

**Comment by jmc529** [comment]
Try following these steps: https://github.com/VCL3D/VolumetricCapture/issues/21#issuecomment-622938983

**Comment by zuru** [comment]
Did you first create/add any devices to `device_repository.json` ?

**Comment by martinpro** [comment]
Hmmm...same with adding device to repository
![image](https://user-images.githubusercontent.com/14353752/107796805-8c1b0f80-6d5a-11eb-82cd-0716efdfe0df.png)

**Comment by martinpro** [comment]
I am trying it also on another pc with same result.

**Comment by martinpro** [comment]
hmmm...moving program to root c:\volcap helps and now works fine. Thank you for trying to help.
