### ISSUE TITLE
Issue with launching volcap.exe

### ISSUE THREAD

**Issue by jmc529** [VCL3D/VolumetricCapture#44]
Hi all,
I am having an issue launching volcap.exe I am unsure what I am doing wrong...
Dependent program versions:
- python 3.9.1
- erlang 23.2
- rabbitmq 3.8.11
- 2015-2019 C++ redistributable 14.23.27820.0 (on both machines)

I have installed rabbitmq and set up a volumetric admin user, added a local azure to my device_repo.json, and have one set up remote. All ports are open inbound and outbound: TCP: 5672, 15672 and UDP: 11234, 320 on the local machine hosting rabbitmq and 321 on the remote machine. 

However, when I open volcap.exe it immediately closes. I opened it in VS19's debugger mode and this is what I was able to see in the command prompt

![image](https://user-images.githubusercontent.com/9061382/107583981-b5f0fc80-6bc9-11eb-9f87-39c2cf1f9125.png)

The exception that shows as "unhanded" in VS19 is 

`Unhandled exception at 0x00007FFCC7383B29 in volcap.exe: Microsoft C++ exception: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> > at memory location 0x0000001B430FD550.`

Please get back to me with and recommendations or let me know if more details would be beneficial.

**Comment by zuru** [comment]
Seems like a networking/socket issue. Can you try with just volcap (no eye running) to see if the app spawns normally?

**Comment by jmc529** [comment]
I had tried that and it did not work. I decided to look through all the firewall rules though and noticed erl was being blocked. (Our university has strict firewall rules). I submitted new firewall rules to the IT department and hopefully that solves it.
