### ISSUE TITLE
System configuration : Check

### ISSUE THREAD

**Issue by meenaldgupta** [VCL3D/VolumetricCapture#49]
I have the following System configuration.... will it work
Intel xeon processor
(Processor	Intel(R) Xeon(R) CPU E5-1607 0 @ 3.00GHz, 3000 Mhz, 4 Core(s), 4 Logical Processor(s))
16 gb ram
250 gb ssd
320 gb hdd
NVIDIA Quadro 2000
Windows 10 pro

**Comment by ankarako** [comment]
Hi @meenaldgupta ,

Thanks for your interest in our project! I am assuming that those are the specifications of your main workstation PC.
Can you give us more details regarding your setup?
How many sensors do you plan to use for your project?

Antonis

**Comment by meenaldgupta** [comment]
yes, the query is regarding workstation PC. 
I have the machine with the above configuration... just want to check will it work.
Right now I am trying the setup for one Realsense D415 Camera.... Once done I will continue the same with 4  Kinect 4 Azure

**Comment by ankarako** [comment]
I suppose that you PC is OK. You can check the minimum requirements [here](https://vcl3d.github.io/VolumetricCapture/docs/software/#volcap).
