### ISSUE TITLE
Remote Eye DLL missing

### ISSUE THREAD

**Issue by MarcKami** [VCL3D/VolumetricCapture#5]
The RemoteEye asset needs blosc.dll

**Comment by vladsterz** [comment]
Hello @MarcKami , 
thank you for pointing this out. We are planning to make a new full release in October where this issue will be resolved.
Best, Vlad

**Comment by vladsterz** [comment]
Hello @MarcKami ,
thank you for pointing this out. If you download [this](https://github.com/VCL3D/VolumetricCapture/releases/tag/2.0) release, were this issue is resolved. Alse, we are planning to make a new full release in October so stay tuned.
Best, Vlad
