### ISSUE TITLE
 Could not load file or assembly Remote_eye_service.exe

### ISSUE THREAD

**Issue by rimand** [VCL3D/VolumetricCapture#53]
I found problem about remote eyes setup.
I opened install_remote_eye_service.bat and than show this message.

![image](https://user-images.githubusercontent.com/17475338/117135276-e7e0bc00-add0-11eb-8234-7250cb17c5a8.png)

I guess it will be about enable remote desktop ,i can't enable remote desktop because i use window home edition. 
How can I solve this problem?

**Comment by ankarako** [comment]
Hi @rimand, 

Thank you for your interest in our project!

Unfortunately, we have never tested `volcap` on Windows 10 Home machines, so I am not exactly sure how to solve your problem.
However, I don't think that remote desktop has anything to do with it (I am not 110% sure though.)

1. The first thing that comes to mind, is that you didn't run the installation script with admin rights.
2. Another thing, could be that some `ENVIRONMENT VARIABLE`s are not in your machine's `PATH`. You can try to install MS Visual Studio (if you don't have it already installed) and run the installation script though Visual Studio's Command prompt.
3. Finally, you can skip the `remote_eye_service` (and not be able to connect automatically with the `remote_eye`s) an try [manual connection](https://vcl3d.github.io/VolumetricCapture/docs/eyes/#manual-sensor-connection)

**Comment by rimand** [comment]
Thankyou,now i see a device connected on rabbitmq server.
But i found a new problem message follow under picture,where I turned off the firwall and opened everything with admin.
Is it because I running volcap and remote_eye_k4a on the same machine?
![image](https://user-images.githubusercontent.com/17475338/117148065-11edaa80-ade0-11eb-9fda-225a53b79b9c.png)
how to fix it?

**Comment by ankarako** [comment]
Is there a chance that you didn't (open)[https://vcl3d.github.io/VolumetricCapture/docs/software/#rabbitmq-setup] the rabbitmq port required for messaging?

**Comment by rimand** [comment]
Thankyou.rabbitmq can work.but i have new problem.
After I opened volcap and remote_eye_k4a. When I click to connect the program remote_eye_k4a It just falls off. And I noticed why it refers to drive D, where I don't have Drive D.

![image](https://user-images.githubusercontent.com/17475338/117158899-043d2280-adea-11eb-844b-ab2ed73b541c.png)

**Comment by zuru** [comment]
Have you downloaded and added the depth engine dll as mentioned [here](https://vcl3d.github.io/VolumetricCapture/docs/software/#service--eye) ?

**Comment by rimand** [comment]
Thank it can solve this.
> Have you downloaded and added the depth engine dll as mentioned [here](https://vcl3d.github.io/VolumetricCapture/docs/software/#service--eye) ? 

Now I can connect 4 remote eyes together (without  remote_eye_service) I found a new problem, 
I was unable to calibration, even though it said it was completed, and when I hit load latest, nothing happened. What should I do?

![image](https://user-images.githubusercontent.com/17475338/117418562-c2c18a00-af45-11eb-8f5c-b7d663da98c3.png)

![image](https://user-images.githubusercontent.com/17475338/117418740-f69caf80-af45-11eb-8980-644f3a0e2ab9.png)


`
g2o::SparseOptimizer::optimize: 0 vertices to optimize, maybe forgot to call initializeOptimization()
g2o::SparseOptimizer::initializeOptimization: Attempt to initialize an empty graph
`

**Comment by ankarako** [comment]
That great!
Did you install StructureNet as described [here](https://vcl3d.github.io/VolumetricCapture/docs/calibration/installation/#installing-the-calibration-software)?

**Comment by rimand** [comment]
Yes, I installed it, but I have a problem installing the module tinyobj.

![image](https://user-images.githubusercontent.com/17475338/117428294-22bd2e00-af50-11eb-9743-ea7dc730c8e1.png)

So I went to edit the file install.py by comment to install tinyobj and then I installed. tinyobjloader 2.0.0rc7 instead.

![image](https://user-images.githubusercontent.com/17475338/117428225-10db8b00-af50-11eb-89dd-c4ce71176735.png)

The result is that this is not calibation.

![image](https://user-images.githubusercontent.com/17475338/117427703-82670980-af4f-11eb-8c1a-999cdc77a5e8.png)

**Comment by vladsterz** [comment]
@rimand ,
sadly I am not able to recreate your issue on my computer. My first cue would be to try to install the deployed tinyobjloader package (you can find it under the directory __volcap\Data\Executables\Calibration\multisensor_calibration\Resources\external\tinyobjloader__ ) by navigating through a command prompt to this directory and executing __pip install .__ (be sure to uninstall the previous one) .
Please provide us with your system's python version.

**Comment by rimand** [comment]
I am using python version 3.7.9.
I tried uninstalling tinyobjloader and reinstalling it according to the file location that you can tell the result like this.

![image](https://user-images.githubusercontent.com/17475338/117433749-058b5e00-af56-11eb-88a5-7ec7dc246ca6.png)

**Comment by vladsterz** [comment]
This is quite odd! I would try [this](https://github.com/tbenthompson/cppimport/issues/2#issuecomment-812986319) one, after uninstalling pybind11

**Comment by rimand** [comment]
I uninstalled all the modules and reinstalled StructureNet, but I fixed it. requirements.txt A little as follows

![image](https://user-images.githubusercontent.com/17475338/117437444-6a48b780-af5a-11eb-9324-eefabef8095e.png)

It allows me to python install.py it all at once. 
Right now I have a module like this:

![image](https://user-images.githubusercontent.com/17475338/117437604-a714ae80-af5a-11eb-98e2-bd8f9dea9e98.png)

But the calibation problem is still posting the same message.

![image](https://user-images.githubusercontent.com/17475338/117438925-67e75d00-af5c-11eb-8be2-a5a64ef70087.png)

After pressing load latest, nothing happens.

**Comment by vladsterz** [comment]
Nice addition.
As the log shows, It has loaded 0 pointclouds for some reason!
Do you press __capture__ prior to __calibrate__ ?
If not can you please give us an insight on the content of the directory  __volcap/Data/Calibrations__ ?

**Comment by rimand** [comment]
I press capture before calibrate. The file data from the directory you tell is as follows.

![image](https://user-images.githubusercontent.com/17475338/117440644-8a7a7580-af5e-11eb-9eea-8f4d08bc064a.png)

**Comment by vladsterz** [comment]
Could you please share the data with us? I would like to have a closer look and run the calibration procedure on my machine!

**Comment by rimand** [comment]
Sure.
https://drive.google.com/drive/folders/1Emyp9q7ANSgq8qdpl6zmZBnk-YRldNt_?usp=sharing

**Comment by ankarako** [comment]
Seeing the boxes that you utilize, I have note that:
1. The boxes in your images do not have the correct placement. Please see [this](https://vcl3d.github.io/VolumetricCapture/docs/calibration/process/#calibrating-a-volumetric-setup).
2. In addition, It seems that you do not use the boxes we recommend. You should be aware that if you use another kind of packaging boxes they need to match the exact dimensions of [these ones](https://vcl3d.github.io/VolumetricCapture/docs/calibration/assembly/#assembling-the-calibration-structure).

**Comment by vladsterz** [comment]
Seems that we support device names without underscores, fact that we should add to the wiki I guess.
You can use the __device_repository__ tool which supports a rename command, and rename your devices to names that have no underscores! (You could also rename them directly in the device_repository.json file)
Then re-capture and calibrate!
Here is the sample log with the data you send me, after I renamed the devices to match devices to our device_repository.
![image](https://user-images.githubusercontent.com/17708197/117446872-6a8a8800-af45-11eb-828e-54a9a2c5506a.png)

**Comment by rimand** [comment]
I rename every new kinect name. It's KA01, KA02, .. but the message appears the same.

![image](https://user-images.githubusercontent.com/17475338/117449698-76d50c00-af6a-11eb-9afc-ed0c99330e5b.png)

**Comment by rimand** [comment]
Today Thankyou vary much
I'll try to change my Vocap machine in case it will produce different results.

**Comment by rimand** [comment]
After I installed the program on the other computer In this case, I am using python 3.8.10 so I can calibrate it., but I have to check if there are any other factors because the new device I installed is very messy. What I do further is that I only add python to it.

![Capture](https://user-images.githubusercontent.com/17475338/117527495-be08de80-aff6-11eb-8a1b-14e8440e251a.PNG)

**Comment by rimand** [comment]
I want to know if your software can do the image clean like this in realtime or do I have to go to the Post process?
(Clen here means the picture is not missing, such as a loose head hair.)

![image](https://user-images.githubusercontent.com/17475338/117527889-733c9600-aff9-11eb-83e5-0a210b681aa0.png)

**Comment by zuru** [comment]
Currently volcap only captures the raw data without any post-processing.
