### ISSUE TITLE
How to combine .ply file?

### ISSUE THREAD

**Issue by rimand** [VCL3D/VolumetricCapture#54]
Hi,

I have try exported .ply files saw they has 4 .ply files per frame. Then open them in Meshlab and saw that file was not in the same position as in Volcap. Do you have any way to combine these files into one with a good quality? 

Best,

**Comment by zuru** [comment]
See [here](https://vcl3d.github.io/VolumetricCapture/docs/volsnap/) for spatially aligned dumping.
