### ISSUE TITLE
How to export or check external calibration files?

### ISSUE THREAD

**Issue by YinghaoHuang91** [VCL3D/VolumetricCapture#55]
Thanks for making this awesome tool available to the public! 

I have one question about the extrinsic calibration with multiple Azure Kinects: how can I check the value of the calibration or export it to a file? Is there a CLI tool for this purpose?

**Comment by vladsterz** [comment]
Hello @YinghaoHuang91 ,
you can find the calibration data, all intermediate and final results under __volcap/Data/Calibrations__ directory.
No, there is no bundled CLI tool for the calibration procedure used by this system, rather it is a cascade of processes.

**Comment by YinghaoHuang91** [comment]
Many thanks!
