### ISSUE TITLE
How does IKEA boxes with random noise pattern compared with default calibration setting as to calibration accuracy?

### ISSUE THREAD

**Issue by YinghaoHuang91** [VCL3D/VolumetricCapture#57]
Hi I wonder how good it is to glue the random noise pattern on the IKEA boxes for calibration from your experience? 
Is it comparable with the QR based ones, or still worse? 

Also if I'm glad to try other marker based calibration, can I do that with the current release of the system (VoCap)? 
I'm talking about the method used in this project: http://vcl.iti.gr/spacewars/.

**Comment by zuru** [comment]
The random noise pattern was used to improve their depth estimates of the Intel RealSense sensors on the untextured box sides. For the Kinect4Azure it is not really needed. In any case, the (median) average depth from a number of frames is used, which helps remove noise.

The marker-based calibration is not supported in this version. However, the raw color and depth data for each viewpoint are available in the `./Data/Calibrations` folder, so you can use them to your liking.
