### ISSUE TITLE
No camera detected in the widget

### ISSUE THREAD

**Issue by frenchtouchXR** [VCL3D/VolumetricCapture#62]
I added 2 Kinect Azure cameras in the device repository, I start the volcap.exe but the devices are not detected. Could you please help ?

**Comment by zokin** [comment]
Please check if the [services](https://vcl3d.github.io/VolumetricCapture/docs/software/#service--eye) have been [configured](https://vcl3d.github.io/VolumetricCapture/docs/eyes/#automatic-sensor-connection) correctly and are up and running.

**Comment by frenchtouchXR** [comment]
Is enabling remote desktop necessary ? As I work on a family version of windows this option is not available.

**Comment by zokin** [comment]
Not really, it is just for accessing headless mini-PCs easily.

**Comment by frenchtouchXR** [comment]
I had the devices detected but none is streaming (tried with 2 azure kinect)
![volcapnotstreaming](https://user-images.githubusercontent.com/40068776/142725233-07b58c30-9012-48d2-8bc6-a5a7e15bef84.jpg)
.

**Comment by frenchtouchXR** [comment]
I managed to make it work by copying depthengine_2_0.dll to the Capturer directory.

**Comment by frenchtouchXR** [comment]
Now trying to get 2 Kinect Azure streaming on the same computer.

**Comment by ankarako** [comment]
Is the main volcap application running on the same machine that the kinects are connected (and therefore, the `remote_eye_k4a.exe`s run on)?

**Comment by frenchtouchXR** [comment]
The app runs on the same machine than the kinects are connected on (when I start volcap.exe remote_eye_k4a.exe stops). I notice the 2 kinects have the same IP. 192.168.1.11 maybe it has something to do.

**Comment by frenchtouchXR** [comment]
Remote eye send me this message : 

> Logging to: C:\Capturer\bin
> Connected K4A device /w serial no: 000501194612
> Connecting to RabbitMQ broker: amqp://volumetric:capture@195.251.117.104:5672 # Handshake
> Sent hello from 000501194612
> Waiting for welcome (press 'q' to quit) ... 

If I run a second instance the new one crashes.

**Comment by frenchtouchXR** [comment]
Does only one kinect by machine is allowed ?

**Comment by ankarako** [comment]
If everything is connected on the same PC, it makes sense for the kinects to show up with the same IP. However, you will have a problem with this setup, due to the `remote_eye_service`. When a `remote_eye.exe` is running, and volcap opens, the service will kill the remote_eye application to spawn a new one. So that's your issue.
Currently, volcap cannot support `N` kinects connected on the same device.

**Comment by frenchtouchXR** [comment]
OK I'm going to try to connect another kinect to my 2cd machine.

**Comment by frenchtouchXR** [comment]
I got my 2cd machine working with remote eye. 
Machine 0 with Kinect 0 and Volcap
Machine 1 with Kinect 1 
I opened in and out the 11245 port for both machine. 
The machine 0 controls and receive the Kinect 1 streaming. The problem is now the Kinect 0 doesn't stream anymore. Is it possible to have Kinects on both the master machine and the slave machine ?

**Comment by frenchtouchXR** [comment]
I managed to do so by pluging in the Kinect 0 first, make it recognized and then pluging in the kinect 1 and refresh then connect all.

**Comment by zuru** [comment]
Sometimes either a refresh is required, or switching USB ports, and if all fails perhaps a volcap restart may fix this :)
