### ISSUE TITLE
Can I import external calibration files, such as a 4*4 matrix for checkerboard calibration?

### ISSUE THREAD

**Issue by Czh-bit** [VCL3D/VolumetricCapture#63]
Because it is currently difficult to buy the specified box or the similar size, it cannot be calibrated. I want to know what the final calibration document looks like? Can I import calibration files generated by other methods?

**Comment by zuru** [comment]
Yes, you just need to produce a date stamped (e.g. `21-11-02-12-32-02`) folder in `./Data/Calibrations` and within it place an `extrinsics.json` file (attached a [template](https://github.com/VCL3D/VolumetricCapture/files/7579335/extrinsics.zip)) that contains the externally calculated matrices for each `named` viewpoint (with the names being those given via `device_repository.exe`).

Please pay attention that for compatibility to the structure calibration results, we flip the `y` and `z` rows of the matrix, negating the new `z` (old `y`), and that the translation is in meters. You can confirm this by inspecting the printed matrices after using the `Calibration` -> `Load Latest...` menu option.
