### ISSUE TITLE
Volcap.exe crashing

### ISSUE THREAD

**Issue by GuilhermeMEESantos** [VCL3D/VolumetricCapture#65]
Good morning. 

I have been having a problem with volcap.exe always crashing. 

It gives me this: Assertion failed: IsArray(), file D:\_dev\_Projects\urealsenz\imerzion\include\deps\rapidjson\document.h, line 1725

I know that the error is in the need for a device_repository.json file in the Resources folder. 

My question is: How do I create it and what do I need to write in it?

**Comment by zokin** [comment]
Please check this part of the docs: [creating a device repository](https://vcl3d.github.io/VolumetricCapture/docs/configure/#creating-a-device-repository)

**Comment by GuilhermeMEESantos** [comment]
I have read that paragraph already but I still don't know how to do it. Could you provide an example?
Sorry for bothering you like this but this is all new to me. I never used JSON files.

**Comment by GuilhermeMEESantos** [comment]
And thank you for the instant reply.

**Comment by GuilhermeMEESantos** [comment]
![imagem](https://user-images.githubusercontent.com/94906816/144591300-00c78a29-6a12-4fbc-833c-46a22c17a92a.png)
