### ISSUE TITLE
Volcap.exe

### ISSUE THREAD

**Issue by GuilhermeMEESantos** [VCL3D/VolumetricCapture#66]
While starting volcap.exe it gave me this:
Assertion failed: IsArray(), file D:_dev_Projects\urealsenz\imerzion\include\deps\rapidjson\document.h, line 1725

My question is: How do I use the device repository tool to create the device repository file?

Could someone provide examples or even a step by step guide?

**Comment by zokin** [comment]
Ok, for each device:
- Plug it
- Run the `add` command using a distinct name
- The `.json` gets updated
- Unplug it so that the next one can be plugged

Let us know where this process breaks and how so that we can be of more help.

**Comment by GuilhermeMEESantos** [comment]
Ok, but where do I run the add command? On the volcap.exe?

**Comment by GuilhermeMEESantos** [comment]
Or on the dev_repo.exe?

**Comment by GuilhermeMEESantos** [comment]
The thing is that both crash. Volcap.exe with the command I sent above and the dev_repo.exe doesn't even start

**Comment by zokin** [comment]
Even if you run `dev_repo.exe -h`? 

![image](https://user-images.githubusercontent.com/5476245/144597671-0fc75d9c-538a-443c-a06f-a40afe3854e9.png)

**Comment by GuilhermeMEESantos** [comment]
How do I run it?

**Comment by GuilhermeMEESantos** [comment]
On a command prompt? I tried and it doesn't recognize the command

**Comment by zokin** [comment]
On which path do you run it from?

**Comment by GuilhermeMEESantos** [comment]
On the C:\Windows\system32

**Comment by GuilhermeMEESantos** [comment]
How do I change the path?

**Comment by GuilhermeMEESantos** [comment]
Ok, already have C:\volcap

**Comment by zokin** [comment]
Please resolve these issues and check the documentation again as well as past issues to move forward with settings this up.

**Comment by GuilhermeMEESantos** [comment]
I tried adding a camera and it shows me this:

C:\volcap>dev_repo.exe -- add device_name --cam_type 1
The following arguments were not expected: -- add device_name --cam_type 1
Run with --help for more information.
[2021-12-03 12:10:49.319] [error] [t=12664] D:\Projects\libs\Azure-Kinect-Sensor-SDK-master\src\dynlib\dynlib_windows.c (115): dynlib_create(). Failed to load DLL depthengine_2_0 with error code: 126
[2021-12-03 12:10:49.320] [error] [t=12664] D:\Projects\libs\Azure-Kinect-Sensor-SDK-master\src\deloader\deloader.cpp (75): deloader_init_once(). Failed to Load Depth Engine Plugin (depthengine). Depth functionality will not work
[2021-12-03 12:10:49.321] [error] [t=12664] D:\Projects\libs\Azure-Kinect-Sensor-SDK-master\src\deloader\deloader.cpp (76): deloader_init_once(). Make sure the depth engine plugin is in your loaders path

**Comment by zokin** [comment]
There is a space between the dashes and add.

**Comment by GuilhermeMEESantos** [comment]
Now it gives the same error:

Assertion failed: IsArray(), file D:\_dev\_Projects\urealsenz\immerzion\include\deps\rapidjson\document.h, line 1725

**Comment by GuilhermeMEESantos** [comment]
I have the empty file created though

**Comment by GuilhermeMEESantos** [comment]
I deleted it and it created the file. 
Thank you for your attention and for your help!
Thank you so much!

Hope you have a great day
