### ISSUE TITLE
remote_eye_service.exe doesn't install

### ISSUE THREAD

**Issue by GuilhermeMEESantos** [VCL3D/VolumetricCapture#67]
Good afternoon. 

I am trying to connect an Intel Realsense D415 to an Intel NUC8i7BEH and in turn connecting directly to my personal pc with an ethernet cable.

After configuring the needed ports, TCP 5672 and 15672 and UCDP 11234, and creating the Capturer file and putting the bin and remote files in it, I tried installing the remote eye service with administrative rights but it gave this:

**Exception occurred while initializing the installation:
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Capturer\remote_eye_service\remote_eye_service.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515).

C:\Capturer\remote_eye_service>net start remote_eye_service
The service name is invalid.**

Could it be the fact that I am using Windows 10 Education on the Intel NUC? Or is it something else missing? Do I need to configure the ports 320 and 321 needed for the synchronization? Could it be the fact Python is not installed in the NUC?

Or alternatively, should I try and connect the devices manually? In that case, I would need to go to the device with the Volcap and use the remote_eye_{k4a|rs2}.exe command. With what directory can I use the remote_eye_{k4a|rs2}.exe command on the command prompt?

**Comment by ankarako** [comment]
Hi @GuilhermeMEESantos and thank you for your interest in our project.

First, Windows Education edition could be the reason that the service cannot be installed, however, I'm not 100% sure because we haven't tried it.
To connect manually to the remote eyes, you should first open volcap on your main PC, and then run the remote_eye_rs2.exe (since you are using Realsense sensors) on the NUC through the command line. Please check [here](https://vcl3d.github.io/VolumetricCapture/docs/eyes/#manual-sensor-connection) for info on how to do this.

**Comment by GuilhermeMEESantos** [comment]
But I can only start Volcap after adding a device to the device repository JSON file, right?

So I first do that and then run the remote_eye_rs2.exe on the NUC?

**Comment by GuilhermeMEESantos** [comment]
It doesn't let me add a new device because:

FATAL [12596] [main@145] "-add" command failed, no IntelRealsense devices connected, please connect one.

But both my computer and the Intel NUC are comunicating with each other, at least I can ping between.

**Comment by GuilhermeMEESantos** [comment]
On the NUC the command prompt sent the HELLO but it is taking a long time to wait for the response and in the volcap command prompt it shows this in yellow:

Connecting to broker: { amqp://volumetric:capture@192.168.0.101:5672}

**Comment by ankarako** [comment]
Did the device appear on volcap when you ran remote_eye_rs2.exe?

**Comment by GuilhermeMEESantos** [comment]
It did let me add it to the device_repository.

Actually it even created the JSON file and added it.

![imagem](https://user-images.githubusercontent.com/94906816/144886815-de6d5f66-ae36-4662-9ea0-10f1af199c15.png)

**Comment by GuilhermeMEESantos** [comment]
But it doesn't show on the program
![imagem](https://user-images.githubusercontent.com/94906816/144886916-ff53cb31-431f-4e81-ba60-779a7cb51a0d.png)

**Comment by GuilhermeMEESantos** [comment]
Most likely because it is still trying to make the connection

**Comment by ankarako** [comment]
The device_repository, does not have anything to do with either seeing the device on volcap, or connecting with it. Please check first volcap's [workflow](https://vcl3d.github.io/VolumetricCapture/docs/volcap/) to understand how you should operate the program.

**Comment by GuilhermeMEESantos** [comment]
I think I may know the problem. Volcap is not connecting to the RabbitMQ broker. I will try and open Volcap with this command:

volcap.exe -b <rabbit_mq_broker_local_ip> -u <rabbit_mq_username> -p <rabbit_mq_password>

As it is shown [here](https://vcl3d.github.io/VolumetricCapture/docs/volcap/#preparation).

**Comment by GuilhermeMEESantos** [comment]
But how do I see what ip is rabbit configured with?

**Comment by GuilhermeMEESantos** [comment]
Or is it associated with my pc's ip?

**Comment by ankarako** [comment]
Where did you install RabbitMQ?

**Comment by GuilhermeMEESantos** [comment]
On both the NUC and my pc

**Comment by GuilhermeMEESantos** [comment]
Was is to install RabbitMQ only in the pc where Volcap will be?

**Comment by ankarako** [comment]
Well, you should install it only on your main PC. Please check the instruction [here](https://vcl3d.github.io/VolumetricCapture/docs/software/).

**Comment by GuilhermeMEESantos** [comment]
Oh, as I was reading I thought it was to install both in the Volcap pc and on the eyes.
So I will uninstall rabbit on the NUC

**Comment by GuilhermeMEESantos** [comment]
What about erlang? Should I uninstall it as well on the NUC?

**Comment by ankarako** [comment]
Yeah, erlang is needed only for rabbit mq

**Comment by GuilhermeMEESantos** [comment]
It's still attempting the connection. But I noticed that the volcap app tries to connect to the RabbitMQ with my pc's ip but the remote_eyes_rs2 attempts with an ip address that is neither my pc's ip neither NUC's

**Comment by GuilhermeMEESantos** [comment]
Do I need to configure RabbitMQ management again?

**Comment by ankarako** [comment]
Do you have more than one network adapters on your PC (wireless, vEthernet)?

**Comment by GuilhermeMEESantos** [comment]
![imagem](https://user-images.githubusercontent.com/94906816/144891721-fb5ed81b-2144-49d7-b93b-fdb4c2766cfb.png)

**Comment by GuilhermeMEESantos** [comment]
I just have these 4 and 2 are disconected
I also had a virtual ethernet adapter but that is disabled so it must not be it.

**Comment by GuilhermeMEESantos** [comment]
No, it is a different one

**Comment by GuilhermeMEESantos** [comment]
Oh so I need to use the remote_eye command on the NUC and set the ip, like it shows [here](![imagem](https://user-images.githubusercontent.com/94906816/144892771-cac0f153-bb95-4cd8-8a5c-1425084b08f1.png)), right?

**Comment by GuilhermeMEESantos** [comment]
![imagem](https://user-images.githubusercontent.com/94906816/144893377-37c22d34-ba5e-4f5e-805b-71d6ddc6e1f2.png)

**Comment by GuilhermeMEESantos** [comment]
I think it worked

**Comment by GuilhermeMEESantos** [comment]
Thank you for your help and for taking the time to help me. Ever since I started trying to create a mocap system using your open-source code that I noticed that the creators were very helpful and took the time to help. 

Wish you a continuation of a good day and of good work.

Best regards,

GuilhermeMEESantos
