### ISSUE TITLE
Point Cloud's point size 

### ISSUE THREAD

**Issue by ttkrpink** [VCL3D/VolumetricCapture#70]
I use the volcap with one eye unit, dump to cdv file, then use volsnap to export to a ply file.

One thing I do notice is the point cloud "resolution" in Meshlab. The point cloud data that I generated from k4arecorder is much "finer" than the volsnap exported ply file. Both point cloud sets are taken at the same distance from the camera. Both point cloud sets are displayed with "Point Size 1" in Meshlab.

Is there a setting where I can change the coarse points to a smaller size?

PS: Thank vcl3d team for sharing this technology and continuing support.

**Comment by zokin** [comment]
Currently, only the low-resolution depth stream is available, and it is not possible to change this from the software somehow. If you try the K4A recorder with the binned version it should be the same.
