### ISSUE TITLE
feasability of implementing this around a basketball court?

### ISSUE THREAD

**Issue by nmjohnson** [VCL3D/VolumetricCapture#76]
Hello,

I was wondering how well this would work if the setup is meant to cover a large space and tracking 10 or individuals? A basketball court is roughly 30m x 15m I would imagine it would take about a dozen sensors to get enough coverage around the court. Any suggestions or tips would be appreciated!

**Comment by ankarako** [comment]
Hi! Thank you for your interest in our project.
As you can imagine we've never tested such a scenario. However, I can think of some of the issues you could face.
* Amount of sensors versus network bandwidth. Currently, while our system can support an arbitrary number of sensors, the network bandwidth is a limiting factor, sometimes causing synchronization issues (we've tested 8 devices capturing in high resolution -RGB, depth @ HD/2- and indeed 1GBit bandwidth is only nearly enough).
* Wide baseline between each sensor and calibration. Our calibration process is implemented taking into account our 1-person capturing use-case. I believe that it would not work at all in wide baselines.
* Sensor-to-subject distance. In a basketball court the subject-to-sensor distance would be really large. You should have in mind that these ToF sensors produce correct results in small distances (~1-2.5m), and the depth error increases with distance.

I think that for such a use-case you should go for a more professional system, comprising DSLR (or other types of professional cameras), and calibration methods that consider wider baselines (such as [[1]](https://ieeexplore.ieee.org/document/6958798), [[2]](https://arxiv.org/pdf/2104.08568.pdf)).
