### ISSUE TITLE
Onnxruntime Error: Protobuf parsing failed

### ISSUE THREAD

**Issue by dbrice01** [VCL3D/VolumetricCapture#78]
When selecting "Process" in the calibration stage in a setup with 4x Kinect cameras and default settings I receive the following error: 

D:\32\s\onnxruntime\core\session\inference_session.cc:220 onnxrunime::Inference_Session::Inference_Session statis.IsOK() was false. Given model could not be parsed while creating inference session. Error message: Protobuf parsing failed

Any ideas?

Thanks.

**Comment by dbrice01** [comment]
![VolCap Screenshot](https://user-images.githubusercontent.com/81298532/173581150-f32173ac-1e28-4cd4-a4c2-3d74b52cf625.PNG)
![VolcCap Calibration Error](https://user-images.githubusercontent.com/81298532/173581517-3eff4b8f-3a35-420c-a2bc-639d1a28767c.PNG)

**Comment by zuru** [comment]
It may be related to `protobuf` breaking backwards compatbility. Try downgrading with `pip install protobuf==3.20.1`

**Comment by dbrice01** [comment]
Thank you for your quick reply and suggestion.

![image](https://user-images.githubusercontent.com/81298532/173814906-d0560fcb-ba13-43ec-89a9-a3dc058eacd1.png)

It seems that the 3.20.1 distribution is missing from pip. Would you recommend I try to install 3.20.1 with an alternative method, or should I try and use one of the available distributions? 

Also, pip version is 21.3.1

Thanks

**Comment by dbrice01** [comment]
Since my last post: I've verified that protobuf version 3.20.1 is installed (after switching from python 3.6 -> 3.7), however the error, "protobuf parsing failed" remains.

Thanks

**Comment by dbrice01** [comment]
Has anyone got any ideas on troubleshooting this?  All of the required packages seem to be in place during the StructureNet install. Thanks

**Comment by zokin** [comment]
Not sure whats up but can you try download the model from gdrive (see installation.txt) and then running these:

![image](https://user-images.githubusercontent.com/5476245/177157482-6be5134e-92f1-4885-bb60-7b5bdc92f794.png)

On my side it seems to be ok with;

```
onnx                         1.8.1
onnxruntime                  1.6.0
protobuf                     3.19.1
```

**Comment by dbrice01** [comment]
Issue was resolved through resetting the Host PC environment with the package versions provided in the comments above. 
Thank you.
