### ISSUE TITLE
dev_repo.exe not creating device_repository.json

### ISSUE THREAD

**Issue by dhorspool** [VCL3D/VolumetricCapture#79]
Each time I try to add a new device by using dev_repo.exe to create a device repository the Json is not created in the resources. The intel realsense cameras are working as I have their viewer working as I try to add them. I am trying only one camera at a time. 

I have tried moving \volcap to C:\. Do I need to create a device_repository.json beforehand? this is not clear from documentation. 
![image](https://user-images.githubusercontent.com/35217363/174106268-91bb7824-835a-4377-b2e7-e0faca365c2c.png)

**Comment by alexd314** [comment]
Hello,
What is the model of you Intel RealSense sensors ?

**Comment by dhorspool** [comment]
When running command prompt in Admin mode, dev_repo progresses further bu still does not appear to create a device_repository.json file 
![image](https://user-images.githubusercontent.com/35217363/174118396-961ecefc-2289-450c-b59f-cecdb2d879df.png)

**Comment by ankarako** [comment]
Could you please check if `device_repository.json` is created somewhere else (such as volcap's binary dir - i.e. the parent directory of the "Resources" folder) this was an issue, and I can't remember if it is resolved.

**Comment by dhorspool** [comment]
Does not appear to be in the volcap binary dir. 
![image](https://user-images.githubusercontent.com/35217363/174120677-93548a56-2edd-4aba-ab9d-84871c9fcf81.png)
I have also tried manually updating the path using "C:\>volcap\dev_repo.exe --path C:\volcap\Resources" .  Also used searched function on file explorer and nothing came up
