### ISSUE TITLE
How to get extrinsic

### ISSUE THREAD

**Issue by terry-r123** [VCL3D/VolumetricCapture#84]
Hi, @zokin @vladsterz 
Thank you for your exciting work!

I would like to know when I only have run `calibration.py` with my own` .pgm` and `.png` files of multiple cameras and got the `calibration.json`, how I select the main camera, and how to get extrinsic of other cameras relative to the main camera

such as:
![image](https://user-images.githubusercontent.com/33857509/187362693-6fb47a2c-42f8-4abb-ac6c-0b1bd2b02f06.png)

I would like to know how to get the external reference of camera k4a2982 with respect to camera k4a3495

Thanks!!!

**Comment by ankarako** [comment]
Hi @terry-r123 ,

Unfortunately this information is not captured by the system. Every camera is registered individually.

**Comment by terry-r123** [comment]
> Hi @terry-r123 ,
> 
> Unfortunately this information is not captured by the system. Every camera is registered individually.

Thanks,  @ankarako .
Can I make cameras horizontally to calibrate, because we want to shoot video horizontally to widen the field of view
