### ISSUE TITLE
2 Nodes Camera Handshake Error

### ISSUE THREAD

**Issue by MarcKami** [VCL3D/VolumetricCapture#9]
If you have 2 nodes with 4 cameras each, you run 1 of them and then you "handshake" with your node's cameras and the other node as well. This is a problem because if you starts one of them, then the other blocks the first one when "handshaking" with the first node cameras. Of course the device_repository.json of each node only haves the 4 cameras of the corresponding node.

**Comment by zuru** [comment]
We will probably fix this for the automatic mode in a subsequent release (after the upcoming Kinect 4 Azure one).

For now, the way to overcome this is to disable the services and manually start the `remote_eye` apps and then connect them one-by-one.
