### ISSUE TITLE
How to stream live volumetric data

### ISSUE THREAD

**Issue by DbSundhar** [VCL3D/VolumetricCapture#91]
I want stream volumetric data from volcap.exe

**Comment by ankarako** [comment]
Unfortunately you can't

**Comment by bipul-mohanto** [comment]
Hi @ankarako, but is there any other way, maybe any third-party software to stream live?

**Comment by alexd314** [comment]
Unfortunately this is not possible.

**Comment by bipul-mohanto** [comment]
Okay, that is sad. Is there any alternative to this software that can do that? Sorry, I am just a newbie.
