### ISSUE TITLE
Streaming live data

### ISSUE THREAD

**Issue by bipul-mohanto** [VCL3D/VolumetricCapture#92]
Hi! I already checked previous issues related to streaming live volumetric data, maybe it is not possible with the current software, or maybe a little hope left!

I have the intel nukes and cameras in another room and want to get (1) the data stream from another room under the local network, in addition, I want to (2) visualize the 3D point cloud streaming live. Would you like to give any suggestions on the 2nd part?

**Comment by ankarako** [comment]
Hi bihul,

As we already discussed you cannot stream the point-cloud data. However, you may be able to do what you need in an offline manner. You could capture a sequence, dump the RGB-D data, and use the dumped data in a pytorch workflow.

**Comment by bipul-mohanto** [comment]
Hi @ankarako,

Thanks for your feedback. Just one more question regarding the `streaming`, I saw the [AVoidX](https://github.com/VCL3D/AVoidX) game from your lab where the cameras are streaming the data live to Unity3D, isn't it?

**Comment by ankarako** [comment]
You are correct, but this feature is not available in the volcap releases on github.

**Comment by bipul-mohanto** [comment]
Actually, we desperately need that feature, not for playing games, but 3D streaming on Unity3D, or even better, if could do it in PyTorch. Looking forward to your suggestions.
